### ISSUE TITLE
Getting Template error when i updated to v1.2.3

### ISSUE THREAD

**Issue by udiazulayintel** [mullerpeter/databricks-grafana#73] opened 2024-03-19 17:41 UTC
in grafana log, i see many :
logger=plugin.mullerpeter-databricks-datasource t=2024-03-19T19:37:06.1928575+02:00 level=info msg="LongToWide conversion error" err="can not convert to wide series, expected long format series input but got not series"

which were not before.

Thanks!

**Comment by mullerpeter** [comment] 2024-03-19 18:33
Not sure if that is related to the latest changes, as nothing on that part of the code changed.
Does the error disappear if you disable the long to wide conversion in the advanced settings in the query editor?

**Comment by udiazulayintel** [comment] 2024-03-20 06:25
i will try it, i also updated to a new grafana version ... thx

**Comment by udiazulayintel** [comment] 2024-03-21 08:32
Hi,
well, seems like the error is different, related to the  SessionHandle ?

logger=context traceID=948f5a5f3a6d40eda6be0d05a2c20f58 userId=5 orgId=1 t=2024-03-21T10:28:51.258006+02:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: failed to receive call resource response: rpc error: code = Unknown desc = databricks: execution error: failed to execute query: Invalid SessionHandle: SessionHandle [79cd286f-f47a-4552-8e51-5a2ddb441b34]" remote_addr=10.245.179.50 traceID=948f5a5f3a6d40eda6be0d05a2c20f58
logger=context traceID=948f5a5f3a6d40eda6be0d05a2c20f58 userId=5 orgId=1 t=2024-03-21T10:28:51.258006+02:00 level=error msg="Request Completed" method=POST path=/api/datasources/uid/ca81c5a8-e98d-44d8-95ee-a51cb96f5af7/resources/defaults status=500 remote_addr=10.245.179.50 time_ms=1065 duration=1.0659802s size=148 referer="https://grafanamit.iil.intel.com/d/c05f85d8-d22c-4a37-b967-63eb6baf4f6d/all-labs-trace-poc?orgId=1&refresh=1m" handler=/api/datasources/uid/:uid/resources/*

**Comment by mullerpeter** [comment] 2024-03-23 10:13
This is again the same error as in #61, this happens when the Databricks connection has been idle for too long & the session should be reinitiated. 
With the logic reintroduced by #62 this should be catched, the Databricks session will be refreshed & the query should be run again after the refresh.
This works for me with the plugin version 1.2.3 and on Grafana Version 10.4.1

What version of Grafana are you using, then I'll try to reproduce the error

**Comment by mullerpeter** [comment] 2024-03-23 14:18
And what kind of compute resources are you using for the connection on the Databricks side? Serverless SQL Warehouse, SQL Warehouse or All purpose compute cluster?

**Comment by udiazulayintel** [comment] 2024-03-25 14:16
Thanks!
I am using v10.3.3.
it is not always happening,  as you said, when it is idle for some time - i get it, after refresh all works well...
but, still - bugging :-)

**Comment by mullerpeter** [comment] 2024-06-14 20:55
Hi @udiazulayintel 

[v1.2.6](https://github.com/mullerpeter/databricks-grafana/releases/tag/v1.2.6) introduces a new mechanism to open the Databricks sql connection. This could potentially fix the issue with the invalid session handle errors, but this is just a guess. 
Incase you try the new version let me know if that fixes the issue for you

**Comment by udiazulayintel** [comment] 2024-06-15 15:06
Looks good, i will monitor it – Thanks!

Thanks,
Udi

**Comment by mullerpeter** [comment] 2024-06-28 18:43
@udiazulayintel Did you experience the issue again in the meantime with the new version? Otherwise I would close this issue

**Comment by udiazulayintel** [comment] 2024-06-28 19:13
Hi, yes i do... only for first connection

Udi
________________________________

**Comment by mullerpeter** [comment] 2024-06-28 19:46
Ok this is really strange as this "Invalid SessionHandle" error is catched [here](https://github.com/mullerpeter/databricks-grafana/blob/a534cc30040afa1f1516b79f62330f230a53cdeb/pkg/plugin/plugin.go#L165C1-L166C1) when executing a query and then a new DB connection is created and the query is retried recursively via the same function. So in theory this error should never make it to the frontend...

The only queries NOT going via this retry function currently, are the ones for the code auto completion. So it could be that these are the queries leading to this error being displayed. 

Do you have Code Auto Completion enabled in the Datasource settings? If so, could you disable it and see if the error still occurs?

**Comment by mullerpeter** [comment] 2024-06-28 21:00
@udiazulayintel I just checked the logs again and on initial load of any Dashboards which include a Databricks Datasource the SuggestionProvider is initialised, which fires a query to get the default catalog & schema from databricks. As this query was previously not using the logic to reinit the connection on Invalid SessionHandle errors, it would result in the error you are seeing on first connection (or at least after some idle time).

I fixed this with #83 and v1.2.8 should now finally fix your issue

**Comment by udiazulayintel** [comment] 2024-06-30 13:58
Hi,

It looks like it is resolved in 1.2.9!
Thanks much

Thanks,
Udi

**Closed** 2024-06-30 16:15 UTC
